# Generated by Django 4.1.2 on 2023-03-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ai_yolo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebin',
            name='container_color',
            field=models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='цвет емкости'),
        ),
        migrations.AlterField(
            model_name='imagebin',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='bin'),
        ),
    ]
