# Generated by Django 4.1.2 on 2023-03-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ai_yolo', '0002_alter_imagebin_container_color_alter_imagebin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebin',
            name='object_quantity',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Колличество распознанных объектов'),
        ),
        migrations.AddField(
            model_name='imagebin',
            name='percent',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Процент'),
        ),
    ]
