# Generated by Django 4.1.2 on 2023-03-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ai_yolo', '0003_imagebin_object_quantity_imagebin_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebin',
            name='percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Процент'),
        ),
    ]
